<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books[
    <!ELEMENT book (title?,isbn*,(zipcode|author),publish*)>
    <!ELEMENT title(#PCDATA)>
    <!ELEMENT isbn(#PCDATA)>
    <!ELEMENT zipcode(#PCDATA)>
    <!ELEMENT author(#PCDATA)>
    <!ELEMENT publish(#PCDATA)>

    <!ATTLIST zipcode zname CDATA “232232323”>
    <!ATTLIST publish year CDATA #FIXED “1995”>
    <!ATTLIST title name CDATA #IMPLIED>
    <!ATTLIST isbn no. CDATA #IMPLIED>
]>

<books>
    <book>
        <title attname="name">Science</title>
        <isbn attno="no.">BCAWT01</isbn>
        <zipcode attzip="zname">232232323</zipcode>
        <publish attpub="year">1995</publish>
    </book>

    <book>
        <title attname="name">DSA</title>
        <isbn attno="no.">BCADSA02</isbn>
        <zipcode attzip="zname">002232323</zipcode>
        <publish attpub="year">1995</publish>
    </book>

    <book>
        <title attname="name">Mathematics</title>
        <isbn attno="no.">BCAPAS03</isbn>
        <zipcode attzip="zname">452232323</zipcode>
        <publish attpub="year">1995</publish>
    </book>

    <book>
        <title attname="name">SAD</title>
        <isbn attno="no.">BCASAD04</isbn>
        <zipcode attzip="zname">982232323</zipcode>
        <publish attpub="year">1995</publish>
    </book>

    <book>
        <title attname="name">English</title>
        <isbn attno="no.">BCAJAVA05</isbn>
        <zipcode attzip="zname">232232323</zipcode>
        <publish attpub="year">1995</publish>
    </book>
</books>
